<a href="https://colab.research.google.com/github/SamaSamrin/Data-Cleaning-with-Python/blob/main/data_cleaning_practice_player_stats_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [25]:
df = pd.read_csv("player_stats.csv")

df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  63 non-null     object
 1   Span    63 non-null     object
 2   Mat     63 non-null     int64
 3   Inns    63 non-null     int64
 4   NO      63 non-null     int64
 5   Runs    63 non-null     int64
 6   HS      63 non-null     object
 7   Ave     63 non-null     float64
 8   BF      63 non-null     object
 9   SR      63 non-null     object
 10  100     63 non-null     int64
 11  50      63 non-null     int64
 12  0       63 non-null     object
 13  4s      63 non-null     object
 14  6s      63 non-null     object
dtypes: float64(1), int64(6), object(8)
memory usage: 7.5+ KB

In [4]:
df.describe()

,Mat,Inns,NO,Runs,Ave,100,50
count,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000
mean,78.031746,132.365079,13.777778,6278.634921,53.680317,18.920635,28.015873
std,52.192562,88.907400,11.364126,4137.845252,7.160512,12.783938,19.128169
min,14.000000,20.000000,1.000000,990.000000,48.000000,1.000000,3.000000
25%,23.500000,43.500000,5.000000,2199.500000,49.540000,6.500000,10.500000
50%,79.000000,131.000000,12.000000,6149.000000,51.620000,19.000000,28.000000
75%,118.500000,199.000000,19.000000,9048.500000,56.345000,28.500000,43.000000
max,200.000000,329.000000,49.000000,15921.000000,99.940000,51.000000,68.000000

In [5]:
df.nunique()

Player    63
Span      59
Mat       52
Inns      55
NO        29
Runs      63
HS        58
Ave       62
BF        61
SR        61
100       36
50        37
0         20
4s        63
6s        38
dtype: int64

# Renaming columns

In [27]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='object')

In [28]:
df = df.rename(columns= {'Mat' : 'Matches',
                    'NO': ' Not_Out',
                    'HS' : 'Highest_Score',
                    'Ave' : 'Average',
                    'BF' : 'Balls_Faced',
                    'SR' : 'Strike_Rate'})

df

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

# Separate Player column into Player_Name and Country

In [29]:
df[['Player_Name', 'Country']] = df['Player'].str.split('(', n=1, expand=True)

df

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Player_Name,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,DG Bradman,AUS)
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,PHKD Mendis,SL)
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AC Voges,AUS)
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,RG Pollock,SA)
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,GA Headley,WI)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,KD Walters,AUS)
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,GC Smith,ICC/SA)
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,WH Ponsford,AUS)
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,SJ McCabe,AUS)
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,DR Jardine,ENG)

In [30]:
df['Country'] = df['Country'].str.replace(")", "")

df

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Player_Name,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,DG Bradman,AUS
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,PHKD Mendis,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AC Voges,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,RG Pollock,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,GA Headley,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,KD Walters,AUS
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,GC Smith,ICC/SA
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,WH Ponsford,AUS
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,SJ McCabe,AUS
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,DR Jardine,ENG

## Dropping the Player column since we don't need it anymore

In [38]:
df = df.drop(columns='Player')

In [39]:
df

,Player_Name,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
0,DG Bradman,1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS,1928,1948
1,PHKD Mendis,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA,1963,1970
4,GA Headley,1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,AUS,1965,1981
59,GC Smith,2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA,2002,2014
60,WH Ponsford,1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,AUS,1924,1934
61,SJ McCabe,1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,AUS,1930,1938
62,DR Jardine,1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,ENG,1928,1934

## Reordering the Player_Name column so that it comes first in the table

In [33]:
temp_column_header = df.pop('Player_Name')

In [34]:
df.insert(0, 'Player_Name', temp_column_header)

In [35]:
df

,Player_Name,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country
0,DG Bradman,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS
1,PHKD Mendis,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL
2,AC Voges,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA
4,GA Headley,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,AUS
59,GC Smith,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
60,WH Ponsford,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,AUS
61,SJ McCabe,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,AUS
62,DR Jardine,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,ENG

# Separating the Span column into Rookie_Year and Final_Year

In [40]:
df[['Rookie_Year', 'Final_Year']] = df['Span'].str.split('-', n=1, expand=True)

df = df.drop(columns='Span')

df

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,AUS,1965,1981
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA,2002,2014
60,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,AUS,1924,1934
61,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,AUS,1930,1938
62,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,ENG,1928,1934

# Removing unwanted characters

In [41]:
df['Highest_Score'] = df['Highest_Score'].str.strip('*')

df

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416+,56,10,5,2,104+,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,AUS,1965,1981
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA,2002,2014
60,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,AUS,1924,1934
61,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,AUS,1930,1938
62,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,ENG,1928,1934

In [47]:
df = df.replace(r'[+*-/]', '', regex=True)

df

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800,586,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,6379,5,5,,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,5568,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707,5448,7,11,1,246,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662,4916,15,33,4,525,23,AUS,1965,1981
59,GC Smith,117,205,13,9265,277,48.25,15525,5967,27,38,11,1165,24,ICCSA,2002,2014
60,WH Ponsford,29,48,4,2122,266,48.22,3118,4477,7,6,1,119,0,AUS,1924,1934
61,SJ McCabe,39,62,5,2748,232,48.21,3217,6002,6,13,4,241,5,AUS,1930,1938
62,DR Jardine,22,33,6,1296,127,48.00,2110,2559,1,10,2,53,0,ENG,1928,1934

In [49]:
df['Country'] = df['Country'].str.replace("ICC", "")

df

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800,586,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,6379,5,5,,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,5568,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707,5448,7,11,1,246,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662,4916,15,33,4,525,23,AUS,1965,1981
59,GC Smith,117,205,13,9265,277,48.25,15525,5967,27,38,11,1165,24,SA,2002,2014
60,WH Ponsford,29,48,4,2122,266,48.22,3118,4477,7,6,1,119,0,AUS,1924,1934
61,SJ McCabe,39,62,5,2748,232,48.21,3217,6002,6,13,4,241,5,AUS,1930,1938
62,DR Jardine,22,33,6,1296,127,48.00,2110,2559,1,10,2,53,0,ENG,1928,1934

In [56]:
df[df['Country']=='SA']

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
3,RG Pollock,23,41,4,2256,274,60.97,1707,5448,7,11,1,246,11,SA,1963,1970
17,JH Kallis,166,280,40,13289,224,55.37,28903,4597,45,58,16,1488,97,SA,1995,2013
23,AD Nourse,34,62,7,2960,231,53.81,108,6388,9,14,3,115,6,SA,1935,1951
39,AB de Villiers,114,191,18,8765,278,50.66,16077,5451,22,46,8,1024,64,SA,2004,2018
52,KC Bland,21,39,5,1669,144,49.08,885,3774,3,9,2,123,20,SA,1961,1966
53,B Mitchell,42,80,9,3471,189,48.88,158,2911,8,21,3,41,1,SA,1929,1949
59,GC Smith,117,205,13,9265,277,48.25,15525,5967,27,38,11,1165,24,SA,2002,2014

In [50]:
df.sample(10)

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
28,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,5239,24,33,11,957,51,PAK,1998,2010
32,A Flower,63,112,19,4794,232,51.54,10636,4507,12,27,5,543,20,ZIM,1992,2002
2,AC Voges,20,31,7,1485,269,61.87,2667,5568,5,4,2,186,5,AUS,2015,2016
56,TT Samaraweera,81,132,20,5462,231,48.76,11641,4692,14,30,11,633,7,SL,2001,2013
51,MJ Clarke,115,198,22,8643,329,49.10,15456,5592,28,27,9,978,39,AUS,2004,2015
54,JL Smith,15,25,3,1075,184,48.86,1429,7522,2,6,,111,26,ENG,2024,2025
48,CP Mead,17,26,2,1185,182,49.37,619,3004,4,3,3,38,0,ENG,1911,1928
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,6379,5,5,,137,24,SL,2022,2025
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI,1930,1954
7,KF Barrington,82,131,15,6806,256,58.67,4957,4242,20,35,5,591,27,ENG,1955,1968

# Checking for empty or null values and handling them

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    63 non-null     object
 1   Matches        63 non-null     int64
 2   Inns           63 non-null     int64
 3    Not_Out       63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest_Score  63 non-null     object
 6   Average        63 non-null     float64
 7   Balls_Faced    63 non-null     object
 8   Strike_Rate    63 non-null     object
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              63 non-null     object
 12  4s             63 non-null     object
 13  6s             63 non-null     object
 14  Country        63 non-null     object
 15  Rookie_Year    63 non-null     object
 16  Final_Year     63 non-null     object
dtypes: float64(1), int64(6), object(10)
memory usage: 8.5+ KB

In [58]:
df = df.replace("", pd.NA)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    63 non-null     object
 1   Matches        63 non-null     int64
 2   Inns           63 non-null     int64
 3    Not_Out       63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest_Score  63 non-null     object
 6   Average        63 non-null     float64
 7   Balls_Faced    60 non-null     object
 8   Strike_Rate    60 non-null     object
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              61 non-null     object
 12  4s             63 non-null     object
 13  6s             63 non-null     object
 14  Country        63 non-null     object
 15  Rookie_Year    63 non-null     object
 16  Final_Year     63 non-null     object
dtypes: float64(1), int64(6), object(10)
memory usage: 8.5+ KB

In [62]:
df.isna().sum().sort_values(ascending=False)

Balls_Faced      3
Strike_Rate      3
0                2
Player_Name      0
Matches          0
Runs             0
 Not_Out         0
Average          0
Inns             0
Highest_Score    0
100              0
50               0
4s               0
6s               0
Country          0
Rookie_Year      0
Final_Year       0
dtype: int64

In [63]:
df = df.fillna(0)

In [64]:
df.isna().sum().sort_values(ascending=False)

Player_Name      0
Matches          0
Inns             0
 Not_Out         0
Runs             0
Highest_Score    0
Average          0
Balls_Faced      0
Strike_Rate      0
100              0
50               0
0                0
4s               0
6s               0
Country          0
Rookie_Year      0
Final_Year       0
dtype: int64

# Checking final dataset (so far)

In [68]:
df.sample(10)

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
9,WR Hammond,85,140,16,7249,336,58.45,7491,3807,22,24,4,419,27,ENG,1927,1947
24,SR Tendulkar,200,329,33,15921,248,53.78,29437,5404,51,68,14,2058,69,IND,1989,2013
30,RT Ponting,168,287,29,13378,257,51.85,22782,5872,41,62,17,1509,73,AUS,1995,2012
3,RG Pollock,23,41,4,2256,274,60.97,1707,5448,7,11,1,246,11,SA,1963,1970
55,HonFS Jackson,20,33,4,1415,144,48.79,0,0,5,6,3,51,0,ENG,1893,1905
18,GE Tyldesley,14,20,2,990,122,55.00,178,2921,3,6,2,37,2,ENG,1921,1929
37,SR Waugh,168,260,46,10927,200,51.06,22461,4864,32,50,22,1175,20,AUS,1985,2004
49,V Sehwag,104,180,6,8586,319,49.34,10441,8223,23,32,16,1233,91,IND,2001,2013
16,SPD Smith,119,212,25,10477,239,56.02,19517,5368,36,43,11,1143,62,AUS,2010,2025
21,VG Kambli,17,21,1,1084,227,54.20,1823,5946,4,3,3,124,6,IND,1993,1995