<a href="https://colab.research.google.com/github/SamaSamrin/Data-Cleaning-with-Python/blob/main/data_cleaning_practice_player_stats_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [79]:
df = pd.read_csv("player_stats.csv")

df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  63 non-null     object
 1   Span    63 non-null     object
 2   Mat     63 non-null     int64
 3   Inns    63 non-null     int64
 4   NO      63 non-null     int64
 5   Runs    63 non-null     int64
 6   HS      63 non-null     object
 7   Ave     63 non-null     float64
 8   BF      63 non-null     object
 9   SR      63 non-null     object
 10  100     63 non-null     int64
 11  50      63 non-null     int64
 12  0       63 non-null     object
 13  4s      63 non-null     object
 14  6s      63 non-null     object
dtypes: float64(1), int64(6), object(8)
memory usage: 7.5+ KB

In [4]:
df.describe()

,Mat,Inns,NO,Runs,Ave,100,50
count,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000
mean,78.031746,132.365079,13.777778,6278.634921,53.680317,18.920635,28.015873
std,52.192562,88.907400,11.364126,4137.845252,7.160512,12.783938,19.128169
min,14.000000,20.000000,1.000000,990.000000,48.000000,1.000000,3.000000
25%,23.500000,43.500000,5.000000,2199.500000,49.540000,6.500000,10.500000
50%,79.000000,131.000000,12.000000,6149.000000,51.620000,19.000000,28.000000
75%,118.500000,199.000000,19.000000,9048.500000,56.345000,28.500000,43.000000
max,200.000000,329.000000,49.000000,15921.000000,99.940000,51.000000,68.000000

In [5]:
df.nunique()

Player    63
Span      59
Mat       52
Inns      55
NO        29
Runs      63
HS        58
Ave       62
BF        61
SR        61
100       36
50        37
0         20
4s        63
6s        38
dtype: int64

# Renaming columns

In [81]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='object')

In [82]:
df = df.rename(columns= {'Mat' : 'Matches',
                    'NO': 'Not_Out',
                    'HS' : 'Highest_Score',
                    'Ave' : 'Average',
                    'BF' : 'Balls_Faced',
                    'SR' : 'Strike_Rate'})

df

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

# Separate Player column into Player_Name and Country

In [83]:
df[['Player_Name', 'Country']] = df['Player'].str.split('(', n=1, expand=True)

df

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Player_Name,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,DG Bradman,AUS)
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,PHKD Mendis,SL)
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AC Voges,AUS)
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,RG Pollock,SA)
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,GA Headley,WI)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,KD Walters,AUS)
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,GC Smith,ICC/SA)
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,WH Ponsford,AUS)
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,SJ McCabe,AUS)
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,DR Jardine,ENG)

In [84]:
df['Country'] = df['Country'].str.replace(")", "")

df

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Player_Name,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,DG Bradman,AUS
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,PHKD Mendis,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AC Voges,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,RG Pollock,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,GA Headley,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,KD Walters,AUS
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,GC Smith,ICC/SA
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,WH Ponsford,AUS
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,SJ McCabe,AUS
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,DR Jardine,ENG

## Dropping the Player column since we don't need it anymore

In [85]:
df = df.drop(columns='Player')

In [86]:
df

,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Player_Name,Country
0,1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,DG Bradman,AUS
1,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,PHKD Mendis,SL
2,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AC Voges,AUS
3,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,RG Pollock,SA
4,1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,GA Headley,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,KD Walters,AUS
59,2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,GC Smith,ICC/SA
60,1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,WH Ponsford,AUS
61,1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,SJ McCabe,AUS
62,1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,DR Jardine,ENG

## Reordering the Player_Name column so that it comes first in the table

In [87]:
temp_column_header = df.pop('Player_Name')

In [88]:
df.insert(0, 'Player_Name', temp_column_header)

In [89]:
df

,Player_Name,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country
0,DG Bradman,1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS
1,PHKD Mendis,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL
2,AC Voges,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA
4,GA Headley,1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,AUS
59,GC Smith,2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
60,WH Ponsford,1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,AUS
61,SJ McCabe,1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,AUS
62,DR Jardine,1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,ENG

In [90]:
df['Country'] = df['Country'].str.replace("ICC/", "")

df

,Player_Name,Span,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country
0,DG Bradman,1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS
1,PHKD Mendis,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL
2,AC Voges,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA
4,GA Headley,1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,AUS
59,GC Smith,2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,SA
60,WH Ponsford,1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,AUS
61,SJ McCabe,1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,AUS
62,DR Jardine,1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,ENG

# Separating the Span column into Rookie_Year and Final_Year

In [91]:
df[['Rookie_Year', 'Final_Year']] = df['Span'].str.split('-', n=1, expand=True)

df = df.drop(columns='Span')

df

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,AUS,1965,1981
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,SA,2002,2014
60,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,AUS,1924,1934
61,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,AUS,1930,1938
62,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,ENG,1928,1934

# Removing unwanted characters

In [92]:
df['Highest_Score'] = df['Highest_Score'].str.strip('*')

df

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416+,56,10,5,2,104+,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,AUS,1965,1981
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,SA,2002,2014
60,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,AUS,1924,1934
61,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,AUS,1930,1938
62,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,ENG,1928,1934

In [95]:
df = df.replace(r'[\/+\-*]', '', regex=True)

df

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS,1965,1981
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,SA,2002,2014
60,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS,1924,1934
61,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS,1930,1938
62,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG,1928,1934

In [96]:
df[df['Country']=='SA']

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970
17,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,SA,1995,2013
23,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,SA,1935,1951
39,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,SA,2004,2018
52,KC Bland,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,SA,1961,1966
53,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,SA,1929,1949
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,SA,2002,2014

In [97]:
df.sample(10)

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
54,JL Smith,15,25,3,1075,184,48.86,1429,75.22,2,6,,111,26,ENG,2024,2025
36,SM Gavaskar,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,IND,1971,1987
42,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,WI,1974,1991
30,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,AUS,1995,2012
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,SA,2002,2014
13,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,ENG,1908,1930
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI,1930,1954
25,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,WI,1990,2006
56,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,SL,2001,2013
51,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,AUS,2004,2015

# Checking for empty or null values and handling them

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    63 non-null     object
 1   Matches        63 non-null     int64
 2   Inns           63 non-null     int64
 3   Not_Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest_Score  63 non-null     object
 6   Average        63 non-null     float64
 7   Balls_Faced    63 non-null     object
 8   Strike_Rate    63 non-null     object
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              63 non-null     object
 12  4s             63 non-null     object
 13  6s             63 non-null     object
 14  Country        63 non-null     object
 15  Rookie_Year    63 non-null     object
 16  Final_Year     63 non-null     object
dtypes: float64(1), int64(6), object(10)
memory usage: 8.5+ KB

In [99]:
df = df.replace("", pd.NA)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    63 non-null     object
 1   Matches        63 non-null     int64
 2   Inns           63 non-null     int64
 3   Not_Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest_Score  63 non-null     object
 6   Average        63 non-null     float64
 7   Balls_Faced    60 non-null     object
 8   Strike_Rate    60 non-null     object
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              61 non-null     object
 12  4s             63 non-null     object
 13  6s             63 non-null     object
 14  Country        63 non-null     object
 15  Rookie_Year    63 non-null     object
 16  Final_Year     63 non-null     object
dtypes: float64(1), int64(6), object(10)
memory usage: 8.5+ KB

In [101]:
df.isna().sum().sort_values(ascending=False)

Balls_Faced      3
Strike_Rate      3
0                2
Player_Name      0
Matches          0
Runs             0
Not_Out          0
Average          0
Inns             0
Highest_Score    0
100              0
50               0
4s               0
6s               0
Country          0
Rookie_Year      0
Final_Year       0
dtype: int64

In [102]:
df = df.fillna(0)

In [103]:
df.isna().sum().sort_values(ascending=False)

Player_Name      0
Matches          0
Inns             0
Not_Out          0
Runs             0
Highest_Score    0
Average          0
Balls_Faced      0
Strike_Rate      0
100              0
50               0
0                0
4s               0
6s               0
Country          0
Rookie_Year      0
Final_Year       0
dtype: int64

# Changing data types of columns to appropriate ones

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    63 non-null     object
 1   Matches        63 non-null     int64
 2   Inns           63 non-null     int64
 3   Not_Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest_Score  63 non-null     object
 6   Average        63 non-null     float64
 7   Balls_Faced    63 non-null     object
 8   Strike_Rate    63 non-null     object
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              63 non-null     object
 12  4s             63 non-null     object
 13  6s             63 non-null     object
 14  Country        63 non-null     object
 15  Rookie_Year    63 non-null     object
 16  Final_Year     63 non-null     object
dtypes: float64(1), int64(6), object(10)
memory usage: 8.5+ KB

In [105]:
df = df.astype({'Highest_Score' : int,
           'Balls_Faced' : int,
           '0' : int,
           '4s' : int,
           '6s' : int,
           'Rookie_Year' : int,
           'Final_Year' : int,
            'Strike_Rate' : float})

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    63 non-null     object
 1   Matches        63 non-null     int64
 2   Inns           63 non-null     int64
 3   Not_Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest_Score  63 non-null     int64
 6   Average        63 non-null     float64
 7   Balls_Faced    63 non-null     int64
 8   Strike_Rate    63 non-null     float64
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              63 non-null     int64
 12  4s             63 non-null     int64
 13  6s             63 non-null     int64
 14  Country        63 non-null     object
 15  Rookie_Year    63 non-null     int64
 16  Final_Year     63 non-null     int64
dtypes: float64(2), int64(13), object(2)
memory usage: 8.5+ KB

In [107]:
df

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS,1965,1981
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,SA,2002,2014
60,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS,1924,1934
61,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS,1930,1938
62,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG,1928,1934

# Checking final dataset (so far)

In [108]:
df.sample(10)

,Player_Name,Matches,Inns,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Country,Rookie_Year,Final_Year
50,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,PAK,2019,2021
14,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,WI,1948,1960
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970
49,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,IND,2001,2013
15,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,ENG,1937,1955
41,Saud Shakeel,19,36,3,1658,208,50.24,3345,49.56,4,9,2,165,2,PAK,2022,2025
46,InzamamulHaq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,PAK,1992,2007
23,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,SA,1935,1951
56,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,SL,2001,2013
45,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,SL,1997,2014