<a href="https://colab.research.google.com/github/SamaSamrin/Data-Cleaning-with-Python/blob/main/data_cleaning_practice_player_stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("player_stats.csv")

In [3]:
df.head()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  63 non-null     object
 1   Span    63 non-null     object
 2   Mat     63 non-null     int64
 3   Inns    63 non-null     int64
 4   NO      63 non-null     int64
 5   Runs    63 non-null     int64
 6   HS      63 non-null     object
 7   Ave     63 non-null     float64
 8   BF      63 non-null     object
 9   SR      63 non-null     object
 10  100     63 non-null     int64
 11  50      63 non-null     int64
 12  0       63 non-null     object
 13  4s      63 non-null     object
 14  6s      63 non-null     object
dtypes: float64(1), int64(6), object(8)
memory usage: 7.5+ KB

# Renaming columns for better understanding

In [8]:
df = df.rename(columns={ "Mat" : "Matches", "Inns" : "Innings", "NO" : "Not Out", "HS" : "Highest Score", "Ave" : "Average", "BF" : "Balls Faced", "SR" : "Strike Rate" })

In [9]:
df.head()

,Player,Span,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1

# Splitting Player column into 2 : Player_Name & Country

In [16]:
df[['Player_Name', 'Country']] = df['Player'].str.split("(", n=1, expand=True)

In [17]:
df.head()

,Player,Span,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Player_Name,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,DG Bradman,AUS)
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,PHKD Mendis,SL)
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AC Voges,AUS)
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,RG Pollock,SA)
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,GA Headley,WI)

In [18]:
df = df.drop(columns = ["Player"])

df.head()

,Span,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Player_Name,Country
0,1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,DG Bradman,AUS)
1,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,PHKD Mendis,SL)
2,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AC Voges,AUS)
3,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,RG Pollock,SA)
4,1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,GA Headley,WI)

In [19]:
df['Country']  = df['Country'].str.rstrip(")")

df.head()

,Span,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Player_Name,Country
0,1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,DG Bradman,AUS
1,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,PHKD Mendis,SL
2,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AC Voges,AUS
3,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,RG Pollock,SA
4,1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,GA Headley,WI

# Reordering columns to bring the Player_Name column to the front

In [20]:
temp_column_holder = df.pop('Player_Name')

df.insert(0, 'Player', temp_column_holder)

df.head()

,Player,Span,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Country
0,DG Bradman,1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS
1,PHKD Mendis,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL
2,AC Voges,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA
4,GA Headley,1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI

# Splitting Span into 2 columns (Debut_Year & Final_Year)

In [21]:
df[['Debut_Year', 'Final_Year']] = df['Span'].str.split('-', n=1, expand=True)

df.head()

,Player,Span,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Country,Debut_Year,Final_Year
0,DG Bradman,1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS,1928,1948
1,PHKD Mendis,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA,1963,1970
4,GA Headley,1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI,1930,1954

In [22]:
df = df.drop(columns= ['Span'])

df.head()

,Player,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Country,Debut_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI,1930,1954

# Removing undesired or unnecessary characters

In [24]:
#checking how the dataframe looks right now first

df.head(15)

,Player,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Country,Debut_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,WI,1930,1954
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,ENG,1924,1935
6,E Paynter,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,ENG,1931,1939
7,KF Barrington,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,ENG,1955,1968
8,ED Weekes,48,81,5,4455,207,58.61,-,-,15,19,6,258+,2,WI,1948,1958
9,WR Hammond,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,ENG,1927,1947
10,GS Sobers,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,WI,1954,1974
11,HC Brook,30,50,1,2820,317,57.55,3222,87.52,10,13,3,308,47,ENG,2022,2025
12,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,SL,2000,2015
13,JB Hobbs,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,ENG,1908,1930
14,CL Walcott,44,74,7,3798,220,56.68,-,-,15,14,1,107+,11,WI,1948,1960

In [25]:
df["Highest Score"] = df["Highest Score"].str.rstrip('*')

df.head(10)

,Player,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Country,Debut_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416+,56,10,5,2,104+,1,WI,1930,1954
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,ENG,1924,1935
6,E Paynter,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,ENG,1931,1939
7,KF Barrington,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,ENG,1955,1968
8,ED Weekes,48,81,5,4455,207,58.61,-,-,15,19,6,258+,2,WI,1948,1958
9,WR Hammond,85,140,16,7249,336,58.45,7491+,38.07,22,24,4,419+,27,ENG,1927,1947

In [32]:
df['4s'] = df['4s'].str.rstrip('+')

df.head(10)

,Player,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Country,Debut_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,-,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI,1930,1954
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG,1924,1935
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,ENG,1931,1939
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,ENG,1955,1968
8,ED Weekes,48,81,5,4455,207,58.61,-,-,15,19,6,258,2,WI,1948,1958
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,ENG,1927,1947

In [44]:
df['6s'] = df['6s'].str.rstrip("+")

df.head(10)

,Player,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Country,Debut_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI,1930,1954
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG,1924,1935
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,ENG,1931,1939
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,ENG,1955,1968
8,ED Weekes,48,81,5,4455,207,58.61,0,0,15,19,6,258,2,WI,1948,1958
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,ENG,1927,1947

# Removing an invalid character present throughout the dataset

In [37]:
df = df.replace("", pd.NA)

df.head(10)

,Player,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Country,Debut_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,<NA>,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI,1930,1954
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG,1924,1935
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,ENG,1931,1939
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,ENG,1955,1968
8,ED Weekes,48,81,5,4455,207,58.61,<NA>,<NA>,15,19,6,258,2,WI,1948,1958
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,ENG,1927,1947

# Checking the cleaned dataset so far

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         63 non-null     object
 1   Matches        63 non-null     int64
 2   Innings        63 non-null     int64
 3   Not Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest Score  63 non-null     object
 6   Average        63 non-null     float64
 7   Balls Faced    60 non-null     object
 8   Strike Rate    60 non-null     object
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              61 non-null     object
 12  4s             63 non-null     object
 13  6s             63 non-null     object
 14  Country        63 non-null     object
 15  Debut_Year     63 non-null     object
 16  Final_Year     63 non-null     object
dtypes: float64(1), int64(6), object(10)
memory usage: 8.5+ KB

# Fill all the null values with 0 (for now)

In [39]:
df = df.fillna(0)

df.head(10)

,Player,Matches,Innings,Not Out,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Country,Debut_Year,Final_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,SL,2022,2025
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA,1963,1970
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI,1930,1954
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG,1924,1935
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,ENG,1931,1939
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,ENG,1955,1968
8,ED Weekes,48,81,5,4455,207,58.61,0,0,15,19,6,258,2,WI,1948,1958
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,ENG,1927,1947

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         63 non-null     object
 1   Matches        63 non-null     int64
 2   Innings        63 non-null     int64
 3   Not Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest Score  63 non-null     object
 6   Average        63 non-null     float64
 7   Balls Faced    63 non-null     object
 8   Strike Rate    63 non-null     object
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              63 non-null     object
 12  4s             63 non-null     object
 13  6s             63 non-null     object
 14  Country        63 non-null     object
 15  Debut_Year     63 non-null     object
 16  Final_Year     63 non-null     object
dtypes: float64(1), int64(6), object(10)
memory usage: 8.5+ KB

# Changing column data types into appropriate ones

In [45]:
df = df.astype( {'Highest Score' : int,
                'Balls Faced' : int,
                '0' : int,
                '4s' : int,
                '6s' : int,
                'Debut_Year' : int,
                'Final_Year' : int})

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         63 non-null     object
 1   Matches        63 non-null     int64
 2   Innings        63 non-null     int64
 3   Not Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest Score  63 non-null     int64
 6   Average        63 non-null     float64
 7   Balls Faced    63 non-null     int64
 8   Strike Rate    63 non-null     object
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              63 non-null     int64
 12  4s             63 non-null     int64
 13  6s             63 non-null     int64
 14  Country        63 non-null     object
 15  Debut_Year     63 non-null     int64
 16  Final_Year     63 non-null     int64
dtypes: float64(1), int64(13), object(3)
memory usage: 8.5+ KB