<a href="https://colab.research.google.com/github/SamaSamrin/Data-Cleaning-with-Python/blob/main/data_cleaning_practice_player_stats_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("player_stats.csv")

df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [ ]:
df.describe()

,Mat,Inns,NO,Runs,Ave,100,50
count,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000
mean,78.031746,132.365079,13.777778,6278.634921,53.680317,18.920635,28.015873
std,52.192562,88.907400,11.364126,4137.845252,7.160512,12.783938,19.128169
min,14.000000,20.000000,1.000000,990.000000,48.000000,1.000000,3.000000
25%,23.500000,43.500000,5.000000,2199.500000,49.540000,6.500000,10.500000
50%,79.000000,131.000000,12.000000,6149.000000,51.620000,19.000000,28.000000
75%,118.500000,199.000000,19.000000,9048.500000,56.345000,28.500000,43.000000
max,200.000000,329.000000,49.000000,15921.000000,99.940000,51.000000,68.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  63 non-null     object
 1   Span    63 non-null     object
 2   Mat     63 non-null     int64
 3   Inns    63 non-null     int64
 4   NO      63 non-null     int64
 5   Runs    63 non-null     int64
 6   HS      63 non-null     object
 7   Ave     63 non-null     float64
 8   BF      63 non-null     object
 9   SR      63 non-null     object
 10  100     63 non-null     int64
 11  50      63 non-null     int64
 12  0       63 non-null     object
 13  4s      63 non-null     object
 14  6s      63 non-null     object
dtypes: float64(1), int64(6), object(8)
memory usage: 7.5+ KB

In [ ]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='object')

In [ ]:
df = df.rename(columns={'Mat' : 'Matches',
                       'Inns' : 'Innings',
                        'NO' : 'Not_Out',
                        'HS' : 'Highest_Score',
                        'BF' : 'Balls_Faced',
                        'Ave' : 'Average',
                        'SR' : 'Strike_Rate'})

df

,Player,Span,Matches,Innings,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [ ]:
df.columns

Index(['Player', 'Span', 'Matches', 'Innings', 'Not_Out', 'Runs',
       'Highest_Score', 'Average', 'Balls_Faced', 'Strike_Rate', '100', '50',
       '0', '4s', '6s'],
      dtype='object')

# Divide Span into Debut_Year and Final_Year

In [ ]:
df[['Debut_Year', 'Final_Year']] = df['Span'].str.split('-', n=1, expand=True)

df

,Player,Span,Matches,Innings,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Debut_Year,Final_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,2022,2025
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981
59,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
60,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
61,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
62,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

## Deleting the redundant 'Span' column

In [ ]:
df = df.drop(columns='Span')

df

,Player,Matches,Innings,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Debut_Year,Final_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948
1,PHKD Mendis (SL),14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,2022,2025
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981
59,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
60,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
61,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
62,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

# Split Player into Player_Name and Country

In [ ]:
df[['Player_Name', 'Country']] = df['Player'].str.split('(', n=1, expand=True)

df

,Player,Matches,Innings,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Debut_Year,Final_Year,Player_Name,Country
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,DG Bradman,AUS)
1,PHKD Mendis (SL),14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,2022,2025,PHKD Mendis,SL)
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS)
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock,SA)
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954,GA Headley,WI)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,KD Walters,AUS)
59,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA)
60,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,WH Ponsford,AUS)
61,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,SJ McCabe,AUS)
62,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,DR Jardine,ENG)

In [ ]:
df[['Player', 'Player_Name', 'Country']]

               Player   Player_Name  Country
0    DG Bradman (AUS)   DG Bradman      AUS)
1    PHKD Mendis (SL)  PHKD Mendis       SL)
2      AC Voges (AUS)     AC Voges      AUS)
3     RG Pollock (SA)   RG Pollock       SA)
4     GA Headley (WI)   GA Headley       WI)
..                ...           ...      ...
58   KD Walters (AUS)   KD Walters      AUS)
59  GC Smith (ICC/SA)     GC Smith   ICC/SA)
60  WH Ponsford (AUS)  WH Ponsford      AUS)
61    SJ McCabe (AUS)    SJ McCabe      AUS)
62   DR Jardine (ENG)   DR Jardine      ENG)

[63 rows x 3 columns]

In [ ]:
df = df.drop(columns='Player')

df.columns

Index(['Matches', 'Innings', 'Not_Out', 'Runs', 'Highest_Score', 'Average',
       'Balls_Faced', 'Strike_Rate', '100', '50', '0', '4s', '6s',
       'Debut_Year', 'Final_Year', 'Player_Name', 'Country'],
      dtype='object')

In [ ]:
df['Country'] = df['Country'].str.rstrip(')')

df['Country']

0        AUS
1         SL
2        AUS
3         SA
4         WI
       ...
58       AUS
59    ICC/SA
60       AUS
61       AUS
62       ENG
Name: Country, Length: 63, dtype: object

In [ ]:
df['Country'] = df['Country'].str.strip('ICC/')

df['Country']

0     AUS
1      SL
2     AUS
3      SA
4       W
     ...
58    AUS
59     SA
60    AUS
61    AUS
62    ENG
Name: Country, Length: 63, dtype: object

In [ ]:
df

,Matches,Innings,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Debut_Year,Final_Year,Player_Name,Country
0,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,DG Bradman,AUS
1,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,2022,2025,PHKD Mendis,SL
2,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS
3,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock,SA
4,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954,GA Headley,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,KD Walters,AUS
59,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,SA
60,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,WH Ponsford,AUS
61,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,SJ McCabe,AUS
62,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,DR Jardine,ENG

In [ ]:
temp_col_holder = df.pop('Player_Name')

df.insert(0, 'Player_Name', temp_col_holder)

df

,Player_Name,Matches,Innings,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Debut_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,AUS
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,SA
60,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,AUS
61,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,AUS
62,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,ENG

In [ ]:
df.columns

Index(['Player_Name', 'Matches', 'Innings', 'Not_Out', 'Runs', 'Highest_Score',
       'Average', 'Balls_Faced', 'Strike_Rate', '100', '50', '0', '4s', '6s',
       'Debut_Year', 'Final_Year', 'Country'],
      dtype='object')

# Deleting unwanted or invalid characters

In [ ]:
df

,Player_Name,Matches,Innings,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Debut_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316,182*,62.66,2063,63.79,5,5,-,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,AUS
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,SA
60,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,AUS
61,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,AUS
62,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,ENG

In [ ]:
df = df.replace(r'[*+-]', '', regex=True)

df

,Player_Name,Matches,Innings,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Debut_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,1930,1954,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS
59,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,SA
60,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS
61,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS
62,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG

# Changing column data types

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    63 non-null     object
 1   Matches        63 non-null     int64
 2   Innings        63 non-null     int64
 3   Not_Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest_Score  63 non-null     object
 6   Average        63 non-null     float64
 7   Balls_Faced    63 non-null     object
 8   Strike_Rate    63 non-null     object
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              63 non-null     object
 12  4s             63 non-null     object
 13  6s             63 non-null     object
 14  Debut_Year     63 non-null     object
 15  Final_Year     63 non-null     object
 16  Country        63 non-null     object
dtypes: float64(1), int64(6), object(10)
memory usage: 8.5+ KB

## Handling empty cells, so that they don't stop the column data type change

In [ ]:
df = df.replace('', pd.NA)

In [ ]:
df.isna().sum().sort_values(ascending=False)

Balls_Faced      3
Strike_Rate      3
0                2
Player_Name      0
Matches          0
Runs             0
Not_Out          0
Average          0
Innings          0
Highest_Score    0
100              0
50               0
4s               0
6s               0
Debut_Year       0
Final_Year       0
Country          0
dtype: int64

In [ ]:
df = df.fillna(0)

## Now changing the types

In [ ]:
df = df.astype( {'Highest_Score' : int,
            'Balls_Faced' : int,
            'Strike_Rate' : float,
            '0' : int,
            '4s' : int,
            '6s' : int,
            'Debut_Year' : int,
            'Final_Year' : int} )

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    63 non-null     object
 1   Matches        63 non-null     int64
 2   Innings        63 non-null     int64
 3   Not_Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest_Score  63 non-null     int64
 6   Average        63 non-null     float64
 7   Balls_Faced    63 non-null     int64
 8   Strike_Rate    63 non-null     float64
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              63 non-null     int64
 12  4s             63 non-null     int64
 13  6s             63 non-null     int64
 14  Debut_Year     63 non-null     int64
 15  Final_Year     63 non-null     int64
 16  Country        63 non-null     object
dtypes: float64(2), int64(13), object(2)
memory usage: 8.5+ KB

# Checking random samples to see how everything looks

In [ ]:
df.sample(10)

,Player_Name,Matches,Innings,Not_Out,Runs,Highest_Score,Average,Balls_Faced,Strike_Rate,100,50,0,4s,6s,Debut_Year,Final_Year,Country
18,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,ENG
50,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
12,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
31,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,AUS
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,W
39,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
60,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS
47,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,W
62,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG
40,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS

# Checking for some patterns before diving into proper analysis

Which players have the highest scores?

In [ ]:
df[['Player_Name', 'Highest_Score','Country']].sort_values(by='Highest_Score', ascending=False)

          Player_Name  Highest_Score Country
25           BC Lara             400       W
38         ML Hayden             380     AUS
45  DPMD Jayawardene             374      SL
10         GS Sobers             365       W
15          L Hutton             364     ENG
..                ...            ...     ...
1        PHKD Mendis             182      SL
55    Hon.FS Jackson             144     ENG
52          KC Bland             144      SA
62        DR Jardine             127     ENG
18      GE Tyldesley             122     ENG

[63 rows x 3 columns]

Which countries do the players come from?

In [ ]:
df['Country'].unique()

array(['AUS', 'SL', 'SA', 'W', 'ENG', 'NZ', 'ND', 'PAK', 'ZIM'],
      dtype=object)

Which countries do most players come from?

In [ ]:
df['Country'].value_counts()

Country
AUS    15
ENG    14
W       9
SA      7
ND      6
PAK     6
SL      4
NZ      1
ZIM     1
Name: count, dtype: int64

Which players are from Srilanka?

In [ ]:
df[df['Country'] == 'SL'][['Player_Name']]

          Player_Name
1        PHKD Mendis
12     KC Sangakkara
45  DPMD Jayawardene
56    TT Samaraweera

Which players from Australia have the highest scores?

In [ ]:
aus_players_stat = df[ df['Country'] == 'AUS'][['Player_Name', 'Highest_Score']]

aus_players_stat.sort_values(by='Highest_Score', ascending=False)

     Player_Name  Highest_Score
38    ML Hayden             380
0    DG Bradman             334
51    MJ Clarke             329
2      AC Voges             269
60  WH Ponsford             266
30   RT Ponting             257
58   KD Walters             250
22  GS Chappell             247
16    SPD Smith             239
61    SJ McCabe             232
40    AR Border             205
57    RN Harvey             205
31      J Ryder             201
37     SR Waugh             200
33   MEK Hussey             195

# Checking memory usage for the refined dataset

In [60]:
df.memory_usage(deep=True)

Index             132
Player_Name      3787
Matches           504
Innings           504
Not_Out           504
Runs              504
Highest_Score     504
Average           504
Balls_Faced       504
Strike_Rate       504
100               504
50                504
0                 504
4s                504
6s                504
Debut_Year        504
Final_Year        504
Country          3240
dtype: int64

In [61]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    63 non-null     object
 1   Matches        63 non-null     int64
 2   Innings        63 non-null     int64
 3   Not_Out        63 non-null     int64
 4   Runs           63 non-null     int64
 5   Highest_Score  63 non-null     int64
 6   Average        63 non-null     float64
 7   Balls_Faced    63 non-null     int64
 8   Strike_Rate    63 non-null     float64
 9   100            63 non-null     int64
 10  50             63 non-null     int64
 11  0              63 non-null     int64
 12  4s             63 non-null     int64
 13  6s             63 non-null     int64
 14  Debut_Year     63 non-null     int64
 15  Final_Year     63 non-null     int64
 16  Country        63 non-null     object
dtypes: float64(2), int64(13), object(2)
memory usage: 14.4 KB

# Saving the refined or cleaned dataset as a CSV file

In [64]:
df.to_csv('cleaned_player_stats.csv', index=False)
# name of the file
# index=False so that the file isn't generated with the current index as a column